import type { ChatRole } from "./chat-prefs";

/**
 * Strings for the chat replay and its settings. Lifted out of ChatReplay so
 * the settings panel and the user card can share them without importing from
 * the component that renders them.
 */
export const CHAT_COPY = {
  ru: {
    title: "Чат",
    messages: "сообщ.",
    offset: "Сдвиг",
    settings: "Настройки чата",
    offsetAria: "Сдвиг чата в секундах",
    showDeleted: "Показывать удалённые",
    banPermanent: "Пользователь забанен навсегда",
    banTimeout: "Пользователь получил таймаут",
    loading: "Загружаю чат…",
    loadError: "Не удалось загрузить чат. Проверьте соединение с сервером.",
    empty: "Для этого стрима сообщения чата не записались.",
    waiting: "Ожидаю сообщения для текущего момента видео…",
    paused: "Прокрутка чата остановлена — к новым ↓",
    liveEmotes: "Текущие эмоуты канала",
    liveEmotesHint:
      "По умолчанию показываются эмоуты на момент записи. Здесь — набор канала на 7TV прямо сейчас: пригодится, если снапшот не снялся или набор с тех пор пополнился.",
    liveEmotesLoading: "загружаю…",
    liveEmotesError: "не удалось загрузить",
    liveEmotesNone: "у канала нет 7TV",

    sectionView: "Вид",
    sectionHighlight: "Подсветка",
    sectionFilter: "Фильтры",
    fontSize: "Размер текста",
    emoteSize: "Размер эмоутов",
    compact: "Плотно",
    showTimestamps: "Время",
    stripes: "Полосы",
    readableColors: "Читаемые ники",
    readableColorsHint: "Поднимает слишком тёмные цвета ников до читаемых, сохраняя оттенок.",
    highlightFirst: "Первое сообщение",
    keywords: "Ключевые слова",
    keywordsPlaceholder: "ваш ник, розыгрыш",
    keywordsHint: "Через запятую. Сообщения с этими словами получают акцентную полосу.",
    hideCommands: "Скрыть !команды",
    hiddenUsers: "Скрыть пользователей",
    hiddenUsersPlaceholder: "nightbot, streamelements",
    search: "Поиск",
    searchPlaceholder: "текст или ник",
    reset: "Сбросить настройки",
    filtered: "отфильтровано",

    userCardTitle: "История",
    userCardHint: "Сообщения до текущего момента видео",
    userCardEmpty: "К этому моменту пользователь ещё ничего не писал.",
    userCardCount: "сообщ. к этому моменту",
    userCardTotal: "всего за эфир",
    userCardFirst: "первое",
    userCardClose: "Закрыть",
    userCardSeek: "Перемотать к этому сообщению",
    userCardOtherPart: "Это сообщение в другой части записи",
    userCardDeleted: "удалённых",
    userCardDrag: "Потяните, чтобы перенести окно",
    userCardSearch: "Поиск по сообщениям",
    userCardNoMatch: "Ничего не найдено.",
    offsetSaved: "сохранён для этой записи",

    metaViewers: "зрителей",
    metaPeak: "пик",
    metaNoData: "Для этой записи данных об эфире нет.",
    metaReveal: "Показать весь эфир",
    metaRevealHint:
      "По умолчанию видно только то, до чего доиграла запись, — иначе полоса категорий сразу выдаёт, что будет дальше.",
    metaAhead: "дальше",
    metaCategory: "Категория",
  },
  en: {
    title: "Chat",
    messages: "messages",
    offset: "Offset",
    settings: "Chat settings",
    offsetAria: "Chat offset in seconds",
    showDeleted: "Show deleted",
    banPermanent: "User was banned permanently",
    banTimeout: "User was timed out",
    loading: "Loading chat…",
    loadError: "Could not load chat. Check the server connection.",
    empty: "No chat messages were captured for this stream.",
    waiting: "Waiting for messages at this video time…",
    paused: "Chat paused — jump to latest ↓",
    liveEmotes: "Channel's current emotes",
    liveEmotesHint:
      "By default the emotes are the ones from the time of recording. This shows the channel's 7TV set as it is now — useful when no snapshot was taken, or the set has grown since.",
    liveEmotesLoading: "loading…",
    liveEmotesError: "could not load",
    liveEmotesNone: "channel has no 7TV",

    sectionView: "Appearance",
    sectionHighlight: "Highlighting",
    sectionFilter: "Filters",
    fontSize: "Text size",
    emoteSize: "Emote size",
    compact: "Compact",
    showTimestamps: "Timestamps",
    stripes: "Stripes",
    readableColors: "Readable names",
    readableColorsHint: "Lifts author colours that are too dark to read, keeping their hue.",
    highlightFirst: "First message",
    keywords: "Keywords",
    keywordsPlaceholder: "your name, giveaway",
    keywordsHint: "Comma-separated. Messages containing them get an accent bar.",
    hideCommands: "Hide !commands",
    hiddenUsers: "Hide users",
    hiddenUsersPlaceholder: "nightbot, streamelements",
    search: "Search",
    searchPlaceholder: "text or name",
    reset: "Reset settings",
    filtered: "filtered",

    userCardTitle: "History",
    userCardHint: "Messages up to the current video time",
    userCardEmpty: "This user had not written anything by this point.",
    userCardCount: "messages so far",
    userCardTotal: "total this stream",
    userCardFirst: "first",
    userCardClose: "Close",
    userCardSeek: "Jump to this message",
    userCardOtherPart: "This message is in another part of the recording",
    userCardDeleted: "deleted",
    userCardDrag: "Drag to move the window",
    userCardSearch: "Search messages",
    userCardNoMatch: "Nothing found.",
    offsetSaved: "saved for this recording",

    metaViewers: "viewers",
    metaPeak: "peak",
    metaNoData: "No broadcast data was recorded for this stream.",
    metaReveal: "Reveal whole stream",
    metaRevealHint:
      "By default only the part the recording has reached is shown — otherwise the category strip gives away what happens later.",
    metaAhead: "ahead",
    metaCategory: "Category",
  },
} as const;

/** Values widened to string — otherwise the ru literals reject the en table. */
export type ChatCopy = { [K in keyof (typeof CHAT_COPY)["ru"]]: string };

export const ROLE_LABELS: Record<ChatRole, { ru: string; en: string; badge: string }> = {
  broadcaster: { ru: "Стример", en: "Broadcaster", badge: "СТР" },
  moderator: { ru: "Модераторы", en: "Moderators", badge: "MOD" },
  vip: { ru: "VIP", en: "VIP", badge: "VIP" },
  subscriber: { ru: "Подписчики", en: "Subscribers", badge: "SUB" },
  verified: { ru: "Стримеры / ✓", en: "Streamers / ✓", badge: "✓" },
  staff: { ru: "Персонал", en: "Staff", badge: "STAFF" },
  founder: { ru: "Основатели", en: "Founders", badge: "FND" },
  og: { ru: "OG", en: "OG", badge: "OG" },
  sub_gifter: { ru: "Дарители", en: "Gifters", badge: "GIFT" },
  turbo: { ru: "Turbo", en: "Turbo", badge: "T" },
  artist: { ru: "Художники", en: "Artists", badge: "ART" },
};
