const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<!doctype html><html><body><video></video><div id="host"></div></body></html>', {url:'https://www.twitch.tv/videos/123', runScripts:'outside-only', pretendToBeVisual:true});
const w = dom.window;
w.ResizeObserver = class { observe() {} disconnect() {} unobserve() {} };
w.HTMLElement.prototype.scrollTo = function (arg) { this.scrollTop = arg?.top ?? 0; };
const moduleCode = fs.readFileSync('public/twitch-chat.widget.js', 'utf8');
const widget = w.eval(moduleCode + '; TSRChatWidget;');
const video = w.document.querySelector('video');
video.currentTime = 135;
Object.defineProperty(video, 'duration', {value:1000});
const label = '[Y A Y Yes GIF by Djemilah Birnie]';
const gif = 'https://media4.giphy.com/media/joSNxeswxuc74Juo8X/giphy.gif';
const calls = [];
const start = Date.parse('2026-09-13T16:45:00Z');
const poll = { id:'poll', platform:'twitch', kind:'poll', title:'Test poll', status:'resolved', startedAtSec:20, lockedAtSec:null, endedAtSec:60, winningOutcomeId:'one', outcomes:[{id:'one', title:'One', color:null, badgeVersion:null},{id:'two', title:'Two', color:null, badgeVersion:null}], samples:[{atSec:20, status:'active', points:[1,2], users:[1,2]},{atSec:60, status:'resolved', points:[9,3], users:[9,3]}] };
const options = {server:'https://stream.neyron.site', sessions:[{id:'session', recordingStartedAt:new Date(start+100000).toISOString()}], vodStartMs:start,
  video, offset:0, spoilerFree:true, request:async (url) => {
    calls.push(url);
    if (url.includes('/chat?') && !url.includes('cursor=')) return {messages:[{id:'gif', authorLogin:'viewer', textRaw:label, relativeTimeSec:25, gifs:`0-${label.length-1}|joSNxeswxuc74Juo8X|${gif}`}], emotes:null, nextCursor:'next'};
    if (url.includes('cursor=')) return {messages:[{id:'later', authorLogin:'second', textRaw:'Second page', relativeTimeSec:30}], emotes:null};
    if (url.endsWith('/events')) return {events:[poll]};
    if (url.endsWith('/timeline')) return {points:[{relativeTimeSec:0,viewerCount:50,title:'Title',categoryName:'Game'}],segments:[],titles:[],peakViewers:50,averageViewers:50};
    if (url.endsWith('/emotes/live')) return {emotes:null};
    if (url.includes('/history')) return {messages:[],sessions:0};
    throw new Error(url);
  }, onOffsetChange(value) { options.offset=value; instance.update(options); },
};
let instance = widget.mount(w.document.getElementById('host'), options);
const shadow = w.document.getElementById('host').shadowRoot;
const wait = async (condition) => { for(let i=0;i<80;i++){if(condition()) return; await new Promise(r=>setTimeout(r,25));} throw new Error('Timed out: '+shadow.textContent.slice(-2200)); };
(async () => {
  await wait(()=>shadow.querySelector('.chat-gif'));
  assert.equal(shadow.querySelector('.chat-gif img').src, gif);
  assert.match(shadow.textContent, /Second page/);
  await wait(()=>shadow.textContent.includes('Test poll'));
  assert.ok(calls.some(url=>url.includes('cursor=next')));
  assert.equal(w.document.head.querySelector('style'),null,'Widget styles must remain inside Shadow DOM');
  [...shadow.querySelectorAll('button')].find(button=>button.textContent==='viewer').click();
  await wait(()=>shadow.querySelector('.chat-user-card'));
  assert.ok(shadow.querySelector('.chat-user-card .chat-gif img'),'User history reuses GIF rendering in the styled shadow root');
  assert.equal(w.document.body.querySelector('.chat-user-card'),null,'History must not escape into Twitch styles');
  shadow.querySelector('.chat-user-card__close').click();
  await wait(()=>!shadow.querySelector('.chat-user-card'));
  const buttons = [...shadow.querySelectorAll('button')];
  const settings = buttons.find(b => /Настройки чата/.test(b.title || b.getAttribute('aria-label') || ''));
  assert.ok(settings); settings.click();
  await wait(()=>shadow.querySelector('.chat-settings'));
  assert.match(shadow.textContent, /опрос|прогноз/i);
  const size = shadow.querySelector('.chat-settings input[type=range]');
  assert.ok(size);
  const checkboxes = [...shadow.querySelectorAll('.chat-settings input[type=checkbox]')];
  assert.ok(checkboxes.length >= 5 && shadow.querySelectorAll('.chat-chip').length >= 5,'Shared full settings panel');
  checkboxes[0].click();
  await wait(()=>w.localStorage.getItem('tsr-chat-prefs'));
  const minus = [...shadow.querySelectorAll('.chat-settings button')].find(b=>b.title==='-5s');
  minus.click(); await wait(()=>options.offset===5);
  video.currentTime=0; video.dispatchEvent(new w.Event('seeked'));
  await wait(()=>!shadow.textContent.includes('Test poll'));
  assert.ok(!shadow.querySelector('.chat-gif'),'Seeking before message hides future GIF');
  video.currentTime=135; video.dispatchEvent(new w.Event('seeked'));
  await wait(()=>shadow.querySelector('.chat-gif'));
  instance.unmount();
  console.log('PASS shared GIF rendering, complete pagination, poll timeline, settings, persisted preferences, offset sync, seeking and isolated styles');
  dom.window.close();
})().catch(error=>{ console.error(error); dom.window.close(); process.exitCode=1; });
